{% set name = "Protego" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 3466f41438421cf90008e98534d5fde47dc16a17482571d021143ac18b70ace9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/scrapy/protego
  license: BSD-3-Clause-Clear
  license_file: LICENSE
  summary: A pure-Python robots.txt parser with support for modern conventions

extra:
  recipe-maintainers:
    - Gallaecio
